
package endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdminParcelManagerService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:9901/adminService?wsdl")
public class AdminParcelManagerService
    extends Service
{

    private final static URL ADMINPARCELMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINPARCELMANAGERSERVICE_EXCEPTION;
    private final static QName ADMINPARCELMANAGERSERVICE_QNAME = new QName("http://webservice/", "AdminParcelManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9901/adminService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINPARCELMANAGERSERVICE_WSDL_LOCATION = url;
        ADMINPARCELMANAGERSERVICE_EXCEPTION = e;
    }

    public AdminParcelManagerService() {
        super(__getWsdlLocation(), ADMINPARCELMANAGERSERVICE_QNAME);
    }

    public AdminParcelManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINPARCELMANAGERSERVICE_QNAME, features);
    }

    public AdminParcelManagerService(URL wsdlLocation) {
        super(wsdlLocation, ADMINPARCELMANAGERSERVICE_QNAME);
    }

    public AdminParcelManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINPARCELMANAGERSERVICE_QNAME, features);
    }

    public AdminParcelManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminParcelManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ParcelManager
     */
    @WebEndpoint(name = "AdminParcelManagerPort")
    public ParcelManager getAdminParcelManagerPort() {
        return super.getPort(new QName("http://webservice/", "AdminParcelManagerPort"), ParcelManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ParcelManager
     */
    @WebEndpoint(name = "AdminParcelManagerPort")
    public ParcelManager getAdminParcelManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "AdminParcelManagerPort"), ParcelManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINPARCELMANAGERSERVICE_EXCEPTION!= null) {
            throw ADMINPARCELMANAGERSERVICE_EXCEPTION;
        }
        return ADMINPARCELMANAGERSERVICE_WSDL_LOCATION;
    }

}
