
package endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ParcelManager", targetNamespace = "http://webservice/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ParcelManager {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webservice/ParcelManager/addParcelRequest", output = "http://webservice/ParcelManager/addParcelResponse")
    public void addParcel(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webservice/ParcelManager/removeParcelRequest", output = "http://webservice/ParcelManager/removeParcelResponse")
    public void removeParcel(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webservice/ParcelManager/startTrackingParcelRequest", output = "http://webservice/ParcelManager/startTrackingParcelResponse")
    public void startTrackingParcel(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webservice/ParcelManager/updateParcelRouteRequest", output = "http://webservice/ParcelManager/updateParcelRouteResponse")
    public void updateParcelRoute(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ParcelManager/serviceTestRequest", output = "http://webservice/ParcelManager/serviceTestResponse")
    public String serviceTest(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
